### ISSUE TITLE
 plot_ys not found

### ISSUE THREAD

**Issue by davidbp** [sktime/sktime-tutorial-pydata-amsterdam-2020#1]
Hello,

I am trying some of the tutorials with `sktime.__version__ '0.4.3'` but it seems `plotting.forecasting` is not there.

```
from sktime.utils.plotting.forecasting import plot_ys
```
I get
```
ModuleNotFoundError: No module named 'sktime.utils.plotting.forecasting'
```

Is there an equivalent function to make plots?
I tried `plot_series` but it does not work as I expected:

```
y = load_airline()
fig, ax = plot_series(y)
```
```
DateParseError: Unknown datetime string format, unable to parse: x
```

**Comment by davidbp** [comment]
I suggest to update the tutorials with `plot_series` so that they are runable with the current sktime verison. I did a pull request to remove a Warning from `plot_series`.

**Comment by mloning** [comment]
FYI the tutorial was based on v0.4.2 - more up-to-date tutorials can be found on www.sktime.org
