### ISSUE TITLE
dynamic time warping (notebook 03_classification_univariate)

### ISSUE THREAD

**Issue by neodelphis** [sktime/sktime-tutorial-pydata-amsterdam-2020#2]
Thank you so much Markus for your excellent talk.
When reviewing your notebook 03_classification_univariate on K-nearest-neighbours classifier for time series
I noticed that I don't have any difference between euclidean and dtw metrics: both give a score of 0.7
less convincing than the difference you have in the video ;)

**Comment by mloning** [comment]
Thanks @neodelphis and sorry for the late reply, missed the issue here, the tutorial was based on v0.4.2, we're actually working on improvements for the distance-based classification algorithms - more up-to-date tutorials can be found on www.sktime.org
