### ISSUE TITLE
Forecasting in Multivariate time series

### ISSUE THREAD

**Issue by SLTaiwo** [sktime/sktime-tutorial-pydata-amsterdam-2020#4]
Pls, I'll like to know how to handle forecasting in multivariate time series with sktime. 
Let's say I have two time series variables energy load and temperature at hourly intervals and I'm interested in forecasting the load demand for the next 48hrs.
1- Would it suffice to treat this as a univariate time series forcasting by discarding the other variable (temperature)? 
2- If i want to keep both variables but forecast on energy load, how would this be treated with sktime?

Thanks

**Comment by mloning** [comment]
Hi @SLTaiwo please post these questions on the main sktime repo https://github.com/alan-turing-institute/sktime
